routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', 'Auth\AuthController@logout');
Route::name('admin.')->group(function () {
    Route::group(['prefix' => 'dashboard', 'namespace' => 'Admin', 'middleware' => ['auth', 'isAdmin']], function () {

        Route::get('/', 'HomeController@index')->name('index');
        Route::get('user/profile/{id}', 'HomeController@profile')->name('user.profile');
        Route::post('user/profile/{id}', 'HomeController@update')->name('user.update');
        #Route::get('customers', 'HomeController@customers')->name('customers.index');
        //Category
        Route::get('categories', 'CategoriesController@categories');
        Route::get('categories/add/{id?}', 'CategoriesController@addcategory');
        Route::post('savecategory', 'CategoriesController@savecategory');
        Route::get('checkcatname', 'CategoriesController@checkcatname');
        Route::get('editcat/{id}', 'CategoriesController@editcat');
        Route::post('updatecat', 'CategoriesController@updatecat');
        Route::get('delcat/{id}', 'CategoriesController@delcat');
        Route::get('getcategoryById/{id}', 'CategoriesController@getcategoryById');
        Route::get('viewcat/{id}', 'CategoriesController@viewcat');
        Route::get('category/publish', 'CategoriesController@publish');
        Route::get('category/unpublish', 'CategoriesController@unpublish');
        Route::get('category/hidden', 'CategoriesController@hidden');

        Route::resource('shops', 'ShopController');
        Route::resource('users', 'UserController');
        Route::resource('offers', 'OfferController');
        Route::resource('coupons', 'CouponController');
        Route::resource('orders', 'OrderController');
        Route::resource('products', 'ProductController');
        Route::resource('addons', 'AddonController');
        Route::resource('areas', 'AreaController');
        Route::resource('shopareas', 'ShopAreaController');
        Route::resource('shopcategories', 'ShopCategoryController');

        Route::get('shopsbtn/publish', 'ShopController@publish');
        Route::get('shopsbtn/unpublish', 'ShopController@unpublish');
    });
});

Route::group(['prefix' => 'dashboard', 'namespace' => 'Admin'], function () {
    Auth::routes();
    Route::post('/login', 'Auth\LoginController@login')->name('login');
});

app/Http/Controllers/Admin/ShopAreaController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use DB,
    Mail,
    Auth,
    Validator,
    Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Response;
use Config;
use App;
use App\Model\Admin\Shop;
use App\Model\Admin\DeliveryAreaList;
use App\User as AuthUser;
use Hash;
use App\Model\Admin\DeliveryAreaListShop;

class ShopAreaController extends Controller {

    public function index(Request $request) {

        $paginate = 10;
        $areas =  DeliveryAreaListShop::leftjoin('delivery_area_lists','delivery_area_lists.id','=','delivery_area_list_shops.delivery_area')
                  ->select('delivery_area_lists.delivery_area','delivery_area_list_shops.id')  
                  ->where('delivery_area_list_shops.shop_id',Auth::user()->id)->paginate($paginate);
        return view('shoparea.list', compact('areas'));
    }

    public function create() {
        $areas =  DeliveryAreaList::get();
        $area  =  DeliveryAreaListShop::where('shop_id',Auth::user()->id)->pluck('delivery_area')->toArray();
        return view('/shoparea/form',compact('area','areas'));
    } 

    public function store(Request $request) {
        
        if(count($request->delivery_areas)){
            DeliveryAreaListShop::where('shop_id',Auth::user()->id)->delete();
            foreach ($request->delivery_areas as $delivery_area) {
                
                DeliveryAreaListShop::Create(['shop_id' => Auth::user()->id,'delivery_area' => $delivery_area]);
            }
        }    
        
        return Redirect::to('dashboard/shopareas');
    }

    Private function uploadStoreLogo($request) {

        if ($request->hasFile('servicelogo')) {
            $file = $request->file('servicelogo');
            $filename = time().'.'.$file->getClientOriginalExtension();
            $path = public_path() . '/images/offers/';
            $image = '/images/offers/'.$filename;
            $file->move($path, $filename);
        } elseif ($request->has('servicelogo') && $request->servicelogo == '') {
                
                $image = $request->lasthidimg;
        }
        else{
                $image = $request->lasthidimg;
        }
        return $image;    

    }

    public function show($id) {
        $area  = DeliveryAreaList::where('id',$id)->first();
        return view('/shoparea/more', compact('area','areas'));
    }

    public function edit($id) {
        $areas =  DeliveryAreaList::get();
        $area  =  DeliveryAreaListShop::where('shop_id',Auth::user()->id)->pluck('delivery_area')->toArray();
        return view('shoparea.form', compact('area','areas'));
    } 

    public function update(Request $request, $id) {
        $offer = DeliveryAreaList::find($id);
        $offer->update(['shop_id' => 0,'delivery_area' => $request->delivery_area]);
        return Redirect::to('dashboard/shopareas');  
    }

    public function destroy($id) {
        $area = DeliveryAreaListShop::findOrFail($id);
        //$offer->update(['status' => 0]);
        $area->delete();

        return Redirect::to('dashboard/shopareas');  
    }  

    public function checkService(Request $request){

        $service = Servicetype::where('service_name_en',$request->servicename)->first();
        if($service){

            return 1;
        }
        else{

            return 0;
        }
    } 

    public function deleted(){

        $paginate = 10;
        $services =  Servicetype::onlyTrashed()->paginate($paginate);
        return view('/shops/deleted', compact('services'));
    } 

    public function restore($id) {
        $tags = Servicetype::withTrashed()->find($id);
        $tags->restore();
        return Redirect::to('deleted/shops');  
    }     

}

resources/views/shoparea/deleted.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ URL::asset('css/custom_style2.css')}}">
<div class="contentHolderV1">
    <h2>Service Types</h2>
    <div class="col-md-12">
        <div class="col-md-6"> 
             <a href="{{ URL::to('services/create') }}" class="searchbtn">Add Service</a>
        </div>
        <div class="col-md-6"> 
            <a href="{{ URL::to('services') }}" class="searchbtn pull-right">All Services</a>
        </div>
    </div>    
   
    <div class="tableHolder">
        <table style="width: 100%;" class="tableV1" cellpadding="0" cellspacing="0">
            <thead class="tableHeader">
                <tr>
                    <td>#</td>
                    <td>Service Type</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
               
               @foreach($services as $service)
               <?php  //$n++; ?>

                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td><a href="{{ URL::to('services', ['id' => ($service->id)]) }}" class="view">{{ $service->service_name_en }}</a></td>
                        <td><div  class="actions">
                                    <!-- <a href="{{ URL::to('services/'.$service->id.'/edit') }}" class="edit">
                                        <i class="fa fa-edit"></i>
                                    </a> -->
                                    <!-- <a href="{{ URL::to('services', ['id' => ($service->id)]) }}" class="view">
                                        <i class="fa fa-eye"></i>
                                    </a> -->
                                     <a href="{{ URL::to('restore/service', ['id' => ($service->id)]) }}" class="view">
                                       Restore
                                    </a>
                                   <!--   {{ Form::open(['method' => 'DELETE','style'=>"display: inline-block", 'route' => ['services.destroy', $service->id]]) }}
                                        {!! csrf_field() !!}
                                        <a class="delete" data-id=""><i class="fa fa-trash-alt"></i></a>
                                           
                                        {{ Form::close() }} -->
                                    
                                </div></td>
                       
                    </tr>
                    
                     @endforeach
            </tbody>
        </table>
    </div>
<ul class="pagination">
        {!! $services->render() !!}
    </ul>
</div>
<script type="text/javascript">
    
    $(function () {
        $('.delete').click(function(e){
            e.preventDefault();
            if(confirm('Are you sure you want to delete?'))
            {
                $(this).parent('form').submit();
            }else{
                return false;
            }
        });
});
</script>
@endsection

resources/views/shoparea/form.blade.php
@extends('layouts.app')
@section('content')
<!-- muliselect plugin's CSS  -->
<link href="{{asset('assets/plugins/jasny-bootstrap/css/jasny-bootstrap.css')}}" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<style type="text/css">
    .select2-container--default .select2-selection--multiple .select2-selection__choice{
        color: black;
    }
</style>
    <div class="col-md-12 ">
        <div class="box">
            <div class="box-header">
              <h3 class="box-title">@if(isset($offer))Delivery Area Updation @else Delivery Area Creation @endif</small> </h3>
              <!-- tools box -->
              <div class="pull-right box-tools">
                  
                  <a href="{{ URL::to('dashboard/shopareas') }}"><button title="List" data-toggle="tooltip" class="btn btn-default" type="button">
                          <i class="fa fa-list"></i></button>
                  </a>
                
                  @if(isset($offer))
                        <a href="{{ URL::to('dashboard/shopareas/create') }}"><button title="New" data-toggle="tooltip" class="btn btn-default" type="button">
                                <i class="fa fa-plus"></i></button>
                        </a>
                        <a href="{{ URL::to('dashboard/shopareas/'.$area->id) }}"><button title="More" data-toggle="tooltip" class="btn btn-default" type="button">
                                <i class="fa fa-eye"></i></button>
                        </a>

                  @endif
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body pad">
                <div class="flash_messages">
                </div>
                <form id="formSpace" action="{{ URL::to('dashboard/shopareas') }}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                    {!! csrf_field() !!}
                    <!-- First Name-->
                    <div class="form-group {{ $errors->has('delivery_area') ? ' has-error' : '' }}">
                        <label for="delivery_area" class="col-sm-3 control-label required">Delivery Area</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                                <div class="input-group-prepend"></div>
                                <select name="delivery_areas[]" multiple="" class="select2" style="width: 150px;">
                                <option value="">Select Delivery Area</option>
                                @if($areas)
                                    @foreach($areas as $area1)
                                        <option value="{{$area1->id}}" @if(in_array($area1->id, $area)) selected @endif>{{$area1->delivery_area}}</option>
                                    @endforeach
                                @endif
                               </select>

                            </div>
                        </div>
                    </div>
                    

                        
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-6">
                            <button id="btn-submit" type="submit" class="btn btn-default checkbtn">
                                <i class="fa fa-plus"></i> Save
                            </button>
                            <button id="btn-submit" type="button" class="btn btn-default" onclick="window.history.back()">
                                <i class="fa fa-history"></i> Cancel
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
     $('.space_img').change(function(event) {
        var fileSize = this.files[0].size;
        var maxAllowedSize = 2000000;
        if(fileSize > maxAllowedSize){
            $('.errorimg').html('Please upload a smaller file');
           $('.space_img').val('');
        }
        else{
            $('.errorimg').html('');
            if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('.oldpreview').fadeOut();
                        $('.imagePreview').attr('src', e.target.result);
                        $('.imagePreview').fadeIn();
                    }
                    reader.readAsDataURL(this.files[0]);
                }
        }

    });

    /*$('.checkbtn').click(function(){

        var name = $('.service_eng').val();
        $.ajax({
                    type: 'get',
                    url: '<?php echo url('/');?>/checkservice',
                    data: 'servicename='+name,
                    datatype: "json",
                    async: false,
                    cache: false,
                    timeout: 30000,
                        success: function (response) {
                             
                        }
            });
    }); */
     $(document).ready(function() {
    $('.select2').select2();
});
</script>
@endsection

resources/views/shoparea/list.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ URL::asset('css/custom_style2.css')}}">
<style type="text/css">
    a {
    color: #3c8dbc;
    padding: 5px;
}
</style>
<div class="contentHolderV1">
    <h2>Delivery Areas</h2>
    <div class="row">
          <div class="col-md-6"> 
           <!--  <a href="{{ URL::to('deleted/services') }}" class="searchbtn pull-right">Deleted Services</a> -->
        </div>
        <div class=" pull-right" style="float: right;"> 
             <a href="{{ URL::to('dashboard/shopareas/create') }}" class="searchbtn">Add Delivery Area</a>
        </div>
      
    </div>    
   
    <div class="tableHolder">
        <table style="width: 100%;" class="tableV1" cellpadding="0" cellspacing="0">
            <thead class="tableHeader">
                <tr>
                    <td>#</td>
                    <td>Delivery Area</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
               
               @foreach($areas as $service)
               <?php  //$n++; ?>

                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{ $service->delivery_area }}</td>
                        <td><div  class="actions">
                                    <a href="{{ URL::to('dashboard/shopareas/'.$service->id.'/edit') }}" class="edit">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <!-- <a href="{{ URL::to('dashboard/areas', ['id' => ($service->id)]) }}" class="view">
                                        <i class="fa fa-eye"></i>
                                    </a> -->
                                    <form action="{{ route('admin.shopareas.destroy', $service->id) }}" method="post" style="float: left;">
                                         {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                                        <a class="delete" data-id=""><i class="fa fa-trash-alt"></i></a>
                                           
                                         </form>
                                    
                                </div></td>
                       
                    </tr>
                    
                     @endforeach
            </tbody>
        </table>
    </div>
<ul class="pagination">
        {{ $areas->render() }}
    </ul>
</div>
<script type="text/javascript">
    
    $(function () {
        $('.delete').click(function(e){
            e.preventDefault();
            if(confirm('Are you sure you want to delete?'))
            {
                $(this).parent('form').submit();
            }else{
                return false;
            }
        });
});

    
</script>
@endsection

resources/views/shoparea/more.blade.php
@extends('layouts.app')
@section('content')
<style type="text/css">
    .box .row{
         margin-bottom: 15px;
    }
</style>
    <div class="row">
    <div class="col-md-12">
            <div class="col-md-6">
                <h1 class="box-title">Offer Details  </h1>
            </div>    
    <div class="pull-right box-tools">
                    <a href="{{URL::to('dashboard/offers')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default btn-default" type="button" data-original-title="Service List">
                            <i class="fa fa-list"></i>
                        </button>
                    </a>
     @if(isset($offer))
                    <a href="{{URL::to('dashboard/offers/create')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default" type="button" data-original-title="Add Offer">
                            <i class="fa fa-plus"></i>
                        </button>
                    </a>
   
                    <a href="{{URL::to('dashboard/offers/'.$offer->id.'/edit')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default" type="button" data-original-title="Edit Offer">
                            <i class="fa fa-edit"></i>
                        </button>
                    </a>
    @endif               
                </div>
    </div>            
    </div>
        <div class="box">
            <div class="box-body pad" id="tab_1">
                <div class="row">
                    <label class="col-sm-3 control-label">Offer Name</label>
                    <div class="col-sm-6">
                        {{ $offer->name }}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-3 control-label">Offer Value</label>
                    <div class="col-sm-3">
                        {{ $offer->value }}%
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-3 control-label">Offer Image</label>
                    <div class="col-sm-3">
                        @if(!empty($offer->image))
                                    <a href="javascript:void(0)" class="pop" imgsrc="{{asset($offer->space_image)}}"><img src=" {{ asset($offer->image) }}" class="img-responsive img-rounded" width="150" height="1150" /></a>
                        @else
                            <img src="{{asset('assets/images/no-image.png')}}" />
                        @endif
                    </div>
                </div>
              
        </div>
    </div>
@endsection