routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', 'Auth\AuthController@logout');
Route::name('admin.')->group(function () {
    Route::group(['prefix' => 'dashboard', 'namespace' => 'Admin', 'middleware' => ['auth', 'isAdmin']], function () {

        Route::get('/', 'HomeController@index')->name('index');
        Route::get('user/profile/{id}', 'HomeController@profile')->name('user.profile');
        Route::post('user/profile/{id}', 'HomeController@update')->name('user.update');
        #Route::get('customers', 'HomeController@customers')->name('customers.index');
        //Category
        Route::get('categories', 'CategoriesController@categories');
        Route::get('categories/add/{id?}', 'CategoriesController@addcategory');
        Route::post('savecategory', 'CategoriesController@savecategory');
        Route::get('checkcatname', 'CategoriesController@checkcatname');
        Route::get('editcat/{id}', 'CategoriesController@editcat');
        Route::post('updatecat', 'CategoriesController@updatecat');
        Route::get('delcat/{id}', 'CategoriesController@delcat');
        Route::get('getcategoryById/{id}', 'CategoriesController@getcategoryById');
        Route::get('viewcat/{id}', 'CategoriesController@viewcat');
        Route::get('category/publish', 'CategoriesController@publish');
        Route::get('category/unpublish', 'CategoriesController@unpublish');
        Route::get('category/hidden', 'CategoriesController@hidden');

        Route::resource('shops', 'ShopController');
        Route::resource('users', 'UserController');
        Route::resource('offers', 'OfferController');
        Route::resource('coupons', 'CouponController');
        Route::resource('orders', 'OrderController');
        Route::resource('products', 'ProductController');
        Route::resource('addons', 'AddonController');
        Route::resource('areas', 'AreaController');
        Route::resource('shopareas', 'ShopAreaController');
        Route::resource('shopcategories', 'ShopCategoryController');

        Route::get('shopsbtn/publish', 'ShopController@publish');
        Route::get('shopsbtn/unpublish', 'ShopController@unpublish');
    });
});

Route::group(['prefix' => 'dashboard', 'namespace' => 'Admin'], function () {
    Auth::routes();
    Route::post('/login', 'Auth\LoginController@login')->name('login');
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use DB,
    Mail,
    Auth,
    Validator,
    Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Response;
use Config;
use App;
use App\Model\Admin\Shop;
use App\Model\Admin\Offer;
use App\Model\Admin\Coupon;
use App\User as AuthUser;
use Hash;
use App\Model\Admin\ProductAddon;
use App\Model\Admin\Product;
use App\Model\Admin\Tag;
use App\Model\Admin\ProductCustomise;
use App\Model\Admin\Category;
use App\Model\Admin\SizeGroup;

class ProductController extends Controller {

    public function index(Request $request) {
        $paginate = 10;
        if(Auth::user()->role_id == 1){
            $products =  Product::select('products.id','products.name','products.price','shops.name as shopname') 
                       ->leftjoin('shops','shops.user_id','=','products.shop_id')
                       ->where('products.status',1)
                       ->paginate($paginate);
        } else{
            $products =  Product::select('products.id','products.name','products.price','shops.name as shopname') 
                       ->where('products.shop_id',Auth::user()->id)
                       ->leftjoin('shops','shops.user_id','=','products.shop_id')
                       ->where('products.status',1)
                       ->paginate($paginate);
        }
        return view('products.list', compact('products'));
    }

    public function create() {
        $mainCategory = array();
        $category = Category::where('parent_id',0)->where('status',1)->get();
        if($category){
            $i = 0;
            foreach ($category as $cat) {
                $sub = Category::where('parent_id',$cat->id)->where('status',1)->get();
                $mainCategory[$i]['name'] = $cat->name;
                $mainCategory[$i]['id'] = $cat->id;
                $mainCategory[$i]['sub'] = $sub;
                $i++;
            }
        }
        $addons = Product::where('isaddon',1)->where('status',1)->get();
        $sizegroups = SizeGroup::get();
        return view('/products/form',compact('mainCategory','addons','sizegroups'));
    } 

    public function store(Request $request) {
        /*$rules     = array('code' => 'unique:coupons,code',
                    'value' => 'required'
                   );
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput()->with(['flash_error' => "Mandatory fields missing"]);
        } else {*/
        $logo = $this->uploadStoreLogo($request);
        if(isset($request->type)){
            $type = 2;
        } else{
            $type = 1;
        }
        if(isset($request->isaddon)){
            $isaddon = 1;
        } else{
            $isaddon = 0;
        }
        $product = Product::Create(['shop_id' => Auth::user()->id,'name' => $request->name,'image' =>$logo,'price'=>$request->value,'type'=>$type,'isveg'=>$request->isveg,'catgeory'=>$request->catgeory]);
        //'isaddon'=>$isaddon,
        if(isset($request->size)){

            foreach ($request->size as $key => $value) {
                
                if($request->size[$key] && $request->sizeval[$key])
                    ProductCustomise::Create(['product_id'=>$product->id,'name'=>$request->size[$key],'price'=>$request->sizeval[$key]]);
            }
        }
        if(isset($request->addons)){

            foreach ($request->addons as $addon) {
                
                ProductAddon::Create(['product_id'=>$product->id,'name'=>$addon]);
            }
        }
        /*}*/
        return Redirect::to('dashboard/products');
    }

    Private function uploadStoreLogo($request) {

        if ($request->hasFile('servicelogo')) {
            $file = $request->file('servicelogo');
            $filename = time().'.'.$file->getClientOriginalExtension();
            $path = public_path() . '/images/products/';
            $image = '/images/products/'.$filename;
            $file->move($path, $filename);
        } elseif ($request->has('servicelogo') && $request->servicelogo == '') {
                
                $image = $request->lasthidimg;
        }
        else{
                $image = $request->lasthidimg;
        }
        return $image;    

    }

    public function show($id) {
        $product  = Product::where('id',$id)->first();
        $pcutomises = ProductCustomise::where('product_id',$id)->get();
        return view('/products/more', compact('product','pcutomises'));
    }

    public function edit($id) {
        $product  = Product::where('id',$id)->first();
        $mainCategory = array();
        $category = Category::where('parent_id',0)->where('status',1)->get();
        if($category){
            $i = 0;
            foreach ($category as $cat) {
                $sub = Category::where('parent_id',$cat->id)->where('status',1)->get();
                $mainCategory[$i]['name'] = $cat->name;
                $mainCategory[$i]['id'] = $cat->id;
                $mainCategory[$i]['sub'] = $sub;
                $i++;
            }
        }
        $addons = Product::where('isaddon',1)->where('status',1)->get();
        $paddons = ProductAddon::where('product_id',$id)->pluck('name')->toArray();
        $pcutomises = ProductCustomise::where('product_id',$id)->get();
        $sizegroups = SizeGroup::get();
        return view('products.form2', compact('product','mainCategory','addons','paddons','pcutomises','sizegroups'));
    } 

    public function update(Request $request, $id) {
        $product = Product::find($id);
        $logo = $this->uploadStoreLogo($request);
        if(isset($request->type)){
            $type = 2;
        } else{
            $type = 1;
        }
        if(isset($request->isaddon)){
            $isaddon = 1;
        } else{
            $isaddon = 0;
        }
        $product->update(['shop_id' => Auth::user()->id,'name' => $request->name,'image' =>$logo,'price'=>$request->value,'type'=>$type,'isveg'=>$request->isveg,'isaddon'=>$isaddon,'catgeory'=>$request->catgeory]);
        if(isset($request->size)){
            $pcutomises = ProductCustomise::where('product_id',$id)->delete();
            foreach ($request->size as $key => $value) {
                
                if($request->size[$key] && $request->sizeval[$key])
                    ProductCustomise::Create(['product_id'=>$product->id,'name'=>$request->size[$key],'price'=>$request->sizeval[$key]]);
            }
        }
        if(isset($request->addons)){
            $paddons = ProductAddon::where('product_id',$id)->delete();
            foreach ($request->addons as $addon) {
                
                ProductAddon::Create(['product_id'=>$product->id,'name'=>$addon]);
            }
        }
        return Redirect::to('dashboard/products');  
    }

    public function destroy($id) {
        $coupon = Product::findOrFail($id);
        $coupon->update(['status' => 0]);
        //$shop->delete();

        return Redirect::to('dashboard/products');  
    }  

    public function checkService(Request $request){

        $service = Servicetype::where('service_name_en',$request->servicename)->first();
        if($service){

            return 1;
        }
        else{

            return 0;
        }
    } 

    public function deleted(){

        $paginate = 10;
        $services =  Servicetype::onlyTrashed()->paginate($paginate);
        return view('/shops/deleted', compact('services'));
    } 

    public function restore($id) {
        $tags = Servicetype::withTrashed()->find($id);
        $tags->restore();
        return Redirect::to('deleted/shops');  
    }     

}

resources/views/products/deleted.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ URL::asset('css/custom_style2.css')}}">
<div class="contentHolderV1">
    <h2>Service Types</h2>
    <div class="col-md-12">
        <div class="col-md-6"> 
             <a href="{{ URL::to('services/create') }}" class="searchbtn">Add Service</a>
        </div>
        <div class="col-md-6"> 
            <a href="{{ URL::to('services') }}" class="searchbtn pull-right">All Services</a>
        </div>
    </div>    
   
    <div class="tableHolder">
        <table style="width: 100%;" class="tableV1" cellpadding="0" cellspacing="0">
            <thead class="tableHeader">
                <tr>
                    <td>#</td>
                    <td>Service Type</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
               
               @foreach($services as $service)
               <?php  //$n++; ?>

                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td><a href="{{ URL::to('services', ['id' => ($service->id)]) }}" class="view">{{ $service->service_name_en }}</a></td>
                        <td><div  class="actions">
                                    <!-- <a href="{{ URL::to('services/'.$service->id.'/edit') }}" class="edit">
                                        <i class="fa fa-edit"></i>
                                    </a> -->
                                    <!-- <a href="{{ URL::to('services', ['id' => ($service->id)]) }}" class="view">
                                        <i class="fa fa-eye"></i>
                                    </a> -->
                                     <a href="{{ URL::to('restore/service', ['id' => ($service->id)]) }}" class="view">
                                       Restore
                                    </a>
                                   <!--   {{ Form::open(['method' => 'DELETE','style'=>"display: inline-block", 'route' => ['services.destroy', $service->id]]) }}
                                        {!! csrf_field() !!}
                                        <a class="delete" data-id=""><i class="fa fa-trash-alt"></i></a>
                                           
                                        {{ Form::close() }} -->
                                    
                                </div></td>
                       
                    </tr>
                    
                     @endforeach
            </tbody>
        </table>
    </div>
<ul class="pagination">
        {!! $services->render() !!}
    </ul>
</div>
<script type="text/javascript">
    
    $(function () {
        $('.delete').click(function(e){
            e.preventDefault();
            if(confirm('Are you sure you want to delete?'))
            {
                $(this).parent('form').submit();
            }else{
                return false;
            }
        });
});
</script>
@endsection

resources/views/products/list.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ URL::asset('css/custom_style2.css')}}">
<style type="text/css">
    a {
    color: #3c8dbc;
    padding: 5px;
}
</style>
<div class="contentHolderV1">
    <h2>Products</h2>
    <div class="row">
          <div class="col-md-6"> 
           <!--  <a href="{{ URL::to('deleted/services') }}" class="searchbtn pull-right">Deleted Services</a> -->
        </div>
        <div class=" pull-right" style="float: right;"> 
             <a href="{{ URL::to('dashboard/products/create') }}" class="searchbtn">Add Product</a>
        </div>
      
    </div>    
   
    <div class="tableHolder">
        <table style="width: 100%;" class="tableV1" cellpadding="0" cellspacing="0">
            <thead class="tableHeader">
                <tr>
                    <td>#</td>
                    <td>Product Name</td>
                    <td>Product Amount</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
               
               @foreach($products as $service)
               <?php  //$n++; ?>

                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{ $service->name }}</td>
                        <td>{{$service->price}}</td>
                        <td><div  class="actions">
                                    <a href="{{ URL::to('dashboard/products/'.$service->id.'/edit') }}" class="edit">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a href="{{ URL::to('dashboard/products', ['id' => ($service->id)]) }}" class="view">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <form action="{{ route('admin.products.destroy', $service->id) }}" method="post" style="float: left;">
                                         {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                                        <a class="delete" data-id=""><i class="fa fa-trash-alt"></i></a>
                                           
                                         </form>
                                    
                                </div></td>
                       
                    </tr>
                    
                     @endforeach
            </tbody>
        </table>
    </div>
<ul class="pagination">
        {{ $products->render() }}
    </ul>
</div>
<script type="text/javascript">
    
    $(function () {
        $('.delete').click(function(e){
            e.preventDefault();
            if(confirm('Are you sure you want to delete?'))
            {
                $(this).parent('form').submit();
            }else{
                return false;
            }
        });
});

    
</script>
@endsection

resources/views/products/more.blade.php
@extends('layouts.app')
@section('content')
<style type="text/css">
    .box .row{
         margin-bottom: 15px;
    }
</style>
    <div class="row">
    <div class="col-md-12">
            <div class="col-md-6">
                <h1 class="box-title">Product Details  </h1>
            </div>    
    <div class="pull-right box-tools">
                    <a href="{{URL::to('dashboard/products')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default btn-default" type="button" data-original-title="Service List">
                            <i class="fa fa-list"></i>
                        </button>
                    </a>
     @if(isset($product))
                    <a href="{{URL::to('dashboard/products/create')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default" type="button" data-original-title="Add Offer">
                            <i class="fa fa-plus"></i>
                        </button>
                    </a>
   
                    <a href="{{URL::to('dashboard/products/'.$product->id.'/edit')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default" type="button" data-original-title="Edit Offer">
                            <i class="fa fa-edit"></i>
                        </button>
                    </a>
    @endif               
                </div>
    </div>            
    </div>
        <div class="box">
            <div class="box-body pad" id="tab_1">
                <div class="row">
                    <label class="col-sm-3 control-label">Product Name</label>
                    <div class="col-sm-6">
                        {{ $product->name }}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-3 control-label">Product Price</label>
                    <div class="col-sm-3">
                        {{ $product->price }}%
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-3 control-label">Product Category</label>
                    <div class="col-sm-3">
                        {{ $product->category }}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-3 control-label">Veg or Non Veg</label>
                    <div class="col-sm-3">
                        {{ $product->isveg }}
                    </div>
                </div>
                @if(count($pcutomises))
                        @foreach($pcutomises as $pcutomise)
                        <div class="row">
                        <label for="value" class="col-sm-3 control-label required">Customizable Product options</label>
                        <div class="col-sm-9">
                            <div class="">
                                <div class="input-group-prepend"></div>
                                <input type="text" name="size[]" id="value" value='@if(isset($pcutomise)){{ $pcutomise->name }}@endif' class="form-control service_eng"  placeholder="Enter Product Size" style="float: left;width: 30%" readonly="">
                                <input type="text" name="sizeval[]" id="value" value='@if(isset($pcutomise)){{ $pcutomise->price }}@endif' class="form-control service_eng"  placeholder="Enter Product Value" style="float: left;width: 30%;margin-left: 10px;" readonly="">
                                @if ($errors->has('value'))value
                                    <span class="help-block">
                                        <strong>{{ $errors->first('value') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div> 
                        @endforeach
                    @endif  
                <div class="row">
                    <label class="col-sm-3 control-label">Product Image</label>
                    <div class="col-sm-3">
                        @if(!empty($product->image))
                                    <a href="javascript:void(0)" class="pop" imgsrc="{{asset($product->space_image)}}"><img src=" {{ asset($product->image) }}" class="img-responsive img-rounded" width="150" height="1150" /></a>
                        @else
                            <img src="{{asset('assets/images/no-image.png')}}" />
                        @endif
                    </div>
                </div>
              
        </div>
    </div>
@endsection