routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', 'Auth\AuthController@logout');
Route::name('admin.')->group(function () {
    Route::group(['prefix' => 'dashboard', 'namespace' => 'Admin', 'middleware' => ['auth', 'isAdmin']], function () {

        Route::get('/', 'HomeController@index')->name('index');
        Route::get('user/profile/{id}', 'HomeController@profile')->name('user.profile');
        Route::post('user/profile/{id}', 'HomeController@update')->name('user.update');
        #Route::get('customers', 'HomeController@customers')->name('customers.index');
        //Category
        Route::get('categories', 'CategoriesController@categories');
        Route::get('categories/add/{id?}', 'CategoriesController@addcategory');
        Route::post('savecategory', 'CategoriesController@savecategory');
        Route::get('checkcatname', 'CategoriesController@checkcatname');
        Route::get('editcat/{id}', 'CategoriesController@editcat');
        Route::post('updatecat', 'CategoriesController@updatecat');
        Route::get('delcat/{id}', 'CategoriesController@delcat');
        Route::get('getcategoryById/{id}', 'CategoriesController@getcategoryById');
        Route::get('viewcat/{id}', 'CategoriesController@viewcat');
        Route::get('category/publish', 'CategoriesController@publish');
        Route::get('category/unpublish', 'CategoriesController@unpublish');
        Route::get('category/hidden', 'CategoriesController@hidden');

        Route::resource('shops', 'ShopController');
        Route::resource('users', 'UserController');
        Route::resource('offers', 'OfferController');
        Route::resource('coupons', 'CouponController');
        Route::resource('orders', 'OrderController');
        Route::resource('products', 'ProductController');
        Route::resource('addons', 'AddonController');
        Route::resource('areas', 'AreaController');
        Route::resource('shopareas', 'ShopAreaController');
        Route::resource('shopcategories', 'ShopCategoryController');

        Route::get('shopsbtn/publish', 'ShopController@publish');
        Route::get('shopsbtn/unpublish', 'ShopController@unpublish');
    });
});

Route::group(['prefix' => 'dashboard', 'namespace' => 'Admin'], function () {
    Auth::routes();
    Route::post('/login', 'Auth\LoginController@login')->name('login');
});

app/Http/Controllers/Admin/OfferController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use DB,
    Mail,
    Auth,
    Validator,
    Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Response;
use Config;
use App;
use App\Model\Admin\Shop;
use App\Model\Admin\Offer;
use App\User as AuthUser;
use Hash;

class OfferController extends Controller {

    public function index(Request $request) {

        $paginate = 10;
        $offers =  Offer::where('status',1)->paginate($paginate);
        return view('offers.list', compact('offers'));
    }

    public function create() {
        return view('/offers/form');
    } 

    public function store(Request $request) {
        $rules     = array('name' => 'unique:offers,name',
                    'value' => 'required'
                   );
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput()->with(['flash_error' => "Mandatory fields missing"]);
        } else {
        $logo = $this->uploadStoreLogo($request);
        Offer::Create(['shop_id' => Auth::user()->id,'name' => $request->name,'image' =>$logo,'value'=>$request->value]);
        }
        return Redirect::to('dashboard/offers');
    }

    Private function uploadStoreLogo($request) {

        if ($request->hasFile('servicelogo')) {
            $file = $request->file('servicelogo');
            $filename = time().'.'.$file->getClientOriginalExtension();
            $path = public_path() . '/images/offers/';
            $image = '/images/offers/'.$filename;
            $file->move($path, $filename);
        } elseif ($request->has('servicelogo') && $request->servicelogo == '') {
                
                $image = $request->lasthidimg;
        }
        else{
                $image = $request->lasthidimg;
        }
        return $image;    

    }

    public function show($id) {
        $offer  = Offer::where('id',$id)->first();
        return view('/offers/more', compact('offer'));
    }

    public function edit($id) {
        $offer  = Offer::where('id',$id)->first();
        return view('offers.form', compact('offer'));
    } 

    public function update(Request $request, $id) {
        $offer = Offer::find($id);
        $logo = $this->uploadStoreLogo($request);
        $offer->update(['shop_id' => Auth::user()->id,'name' => $request->name,'image' =>$logo,'value'=>$request->value]);
        return Redirect::to('dashboard/offers');  
    }

    public function destroy($id) {
        $offer = Offer::findOrFail($id);
        $offer->update(['status' => 0]);
        //$shop->delete();

        return Redirect::to('dashboard/offers');  
    }  

    public function checkService(Request $request){

        $service = Servicetype::where('service_name_en',$request->servicename)->first();
        if($service){

            return 1;
        }
        else{

            return 0;
        }
    } 

    public function deleted(){

        $paginate = 10;
        $services =  Servicetype::onlyTrashed()->paginate($paginate);
        return view('/shops/deleted', compact('services'));
    } 

    public function restore($id) {
        $tags = Servicetype::withTrashed()->find($id);
        $tags->restore();
        return Redirect::to('deleted/shops');  
    }     

}

resources/views/offers/deleted.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ URL::asset('css/custom_style2.css')}}">
<div class="contentHolderV1">
    <h2>Service Types</h2>
    <div class="col-md-12">
        <div class="col-md-6"> 
             <a href="{{ URL::to('services/create') }}" class="searchbtn">Add Service</a>
        </div>
        <div class="col-md-6"> 
            <a href="{{ URL::to('services') }}" class="searchbtn pull-right">All Services</a>
        </div>
    </div>    
   
    <div class="tableHolder">
        <table style="width: 100%;" class="tableV1" cellpadding="0" cellspacing="0">
            <thead class="tableHeader">
                <tr>
                    <td>#</td>
                    <td>Service Type</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
               
               @foreach($services as $service)
               <?php  //$n++; ?>

                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td><a href="{{ URL::to('services', ['id' => ($service->id)]) }}" class="view">{{ $service->service_name_en }}</a></td>
                        <td><div  class="actions">
                                    <!-- <a href="{{ URL::to('services/'.$service->id.'/edit') }}" class="edit">
                                        <i class="fa fa-edit"></i>
                                    </a> -->
                                    <!-- <a href="{{ URL::to('services', ['id' => ($service->id)]) }}" class="view">
                                        <i class="fa fa-eye"></i>
                                    </a> -->
                                     <a href="{{ URL::to('restore/service', ['id' => ($service->id)]) }}" class="view">
                                       Restore
                                    </a>
                                   <!--   {{ Form::open(['method' => 'DELETE','style'=>"display: inline-block", 'route' => ['services.destroy', $service->id]]) }}
                                        {!! csrf_field() !!}
                                        <a class="delete" data-id=""><i class="fa fa-trash-alt"></i></a>
                                           
                                        {{ Form::close() }} -->
                                    
                                </div></td>
                       
                    </tr>
                    
                     @endforeach
            </tbody>
        </table>
    </div>
<ul class="pagination">
        {!! $services->render() !!}
    </ul>
</div>
<script type="text/javascript">
    
    $(function () {
        $('.delete').click(function(e){
            e.preventDefault();
            if(confirm('Are you sure you want to delete?'))
            {
                $(this).parent('form').submit();
            }else{
                return false;
            }
        });
});
</script>
@endsection

resources/views/offers/form.blade.php
@extends('layouts.app')
@section('content')
<!-- muliselect plugin's CSS  -->
<link href="{{asset('assets/plugins/jasny-bootstrap/css/jasny-bootstrap.css')}}" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <div class="col-md-12 ">
        <div class="box">
            <div class="box-header">
              <h3 class="box-title">@if(isset($offer))Offer Updation @else Offer Creation @endif</small> </h3>
              <!-- tools box -->
              <div class="pull-right box-tools">
                  
                  <a href="{{ URL::to('dashboard/shops') }}"><button title="List" data-toggle="tooltip" class="btn btn-default" type="button">
                          <i class="fa fa-list"></i></button>
                  </a>
                
                  @if(isset($offer))
                        <a href="{{ URL::to('dashboard/shops/create') }}"><button title="New" data-toggle="tooltip" class="btn btn-default" type="button">
                                <i class="fa fa-plus"></i></button>
                        </a>
                        <a href="{{ URL::to('dashboard/shops/'.$offer->id) }}"><button title="More" data-toggle="tooltip" class="btn btn-default" type="button">
                                <i class="fa fa-eye"></i></button>
                        </a>

                  @endif
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body pad">
                <div class="flash_messages">
                </div>
                <form id="formSpace" action="{{ URL::to('dashboard/offers') }}@if(isset($offer))/{{ $offer->id }} @endif" method="POST" enctype="multipart/form-data" class="form-horizontal">
                    {!! csrf_field() !!}
                    @if(isset($offer))
                        {{ method_field('PUT') }}
                        <input type="hidden" name="service_id" value="{{$offer->id}}"/>
                    @endif
                    <!-- First Name-->
                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="col-sm-3 control-label required">Offer Name</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                                <div class="input-group-prepend"></div>
                                <input type="text" name="name" id="name" value='@if(isset($offer)){{ $offer->name }}@endif' class="form-control service_eng" required="" placeholder="Enter Offer Name">
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group {{ $errors->has('value') ? ' has-error' : '' }}">
                        <label for="value" class="col-sm-3 control-label required">Offer Value</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                                <div class="input-group-prepend"></div>
                                <input type="text" name="value" id="value" value='@if(isset($offer)){{ $offer->value }}@endif' class="form-control service_eng" required="" placeholder="Enter Offer Value">
                                @if ($errors->has('value'))value
                                    <span class="help-block">
                                        <strong>{{ $errors->first('value') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    



                   
                    <!-- SpaceImage-->
                
                        <div class="form-group">
                                <label for="title_ar" class="col-sm-3 control-label required">Offer Image</label>
                                <div class="imgUploadHolder col-sm-6">
                                    @if(isset($offer->image) && $offer->image != '')
                                    <input type="hidden" name="lasthidimg" value="{{$offer->image}}" class="lasthidimg">
                                    @endif
                                    <div class="col-lg-3">
                                   <input type="file" class="space_img " name="servicelogo" id="space_img"   @if(isset($offer->image) && $offer->image != '')
                                   value="{{$offer->image}}" @else required @endif>
                                  <label class="errorimg" for="imageInput" style="color: red"></label>
                                    <div style="margin-top: 10px;">
                                    <img src="" class="imagePreview" width="150" height="150" style="display: none;">
                                    @if(isset($offer->image) && $offer->image != '')
                                   <img src="<?php echo url('/');?>{{$offer->image}}" width="150" height="150" class="oldpreview">
                                   
                                   @endif
                                   </div>
                                   </div>

                                </div>
                            </div>
                         
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-6">
                            <button id="btn-submit" type="submit" class="btn btn-default checkbtn">
                                <i class="fa fa-plus"></i> Save
                            </button>
                            <button id="btn-submit" type="button" class="btn btn-default" onclick="window.history.back()">
                                <i class="fa fa-history"></i> Cancel
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
     $('.space_img').change(function(event) {
        var fileSize = this.files[0].size;
        var maxAllowedSize = 2000000;
        if(fileSize > maxAllowedSize){
            $('.errorimg').html('Please upload a smaller file');
           $('.space_img').val('');
        }
        else{
            $('.errorimg').html('');
            if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('.oldpreview').fadeOut();
                        $('.imagePreview').attr('src', e.target.result);
                        $('.imagePreview').fadeIn();
                    }
                    reader.readAsDataURL(this.files[0]);
                }
        }

    });

    /*$('.checkbtn').click(function(){

        var name = $('.service_eng').val();
        $.ajax({
                    type: 'get',
                    url: '<?php echo url('/');?>/checkservice',
                    data: 'servicename='+name,
                    datatype: "json",
                    async: false,
                    cache: false,
                    timeout: 30000,
                        success: function (response) {
                             
                        }
            });
    }); */
</script>
@endsection

resources/views/offers/list.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ URL::asset('css/custom_style2.css')}}">
<style type="text/css">
    a {
    color: #3c8dbc;
    padding: 5px;
}
</style>
<div class="contentHolderV1">
    <h2>Offers</h2>
    <div class="row">
          <div class="col-md-6"> 
           <!--  <a href="{{ URL::to('deleted/services') }}" class="searchbtn pull-right">Deleted Services</a> -->
        </div>
        <div class=" pull-right" style="float: right;"> 
             <a href="{{ URL::to('dashboard/offers/create') }}" class="searchbtn">Add Offer</a>
        </div>
      
    </div>    
   
    <div class="tableHolder">
        <table style="width: 100%;" class="tableV1" cellpadding="0" cellspacing="0">
            <thead class="tableHeader">
                <tr>
                    <td>#</td>
                    <td>Offer Name</td>
                    <td>Offer Value</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
               
               @foreach($offers as $service)
               <?php  //$n++; ?>

                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{ $service->name }}</td>
                        <td>{{$service->value}}%</td>
                        <td><div  class="actions">
                                    <a href="{{ URL::to('dashboard/offers/'.$service->id.'/edit') }}" class="edit">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a href="{{ URL::to('dashboard/offers', ['id' => ($service->id)]) }}" class="view">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <form action="{{ route('admin.offers.destroy', $service->id) }}" method="post" style="float: left;">
                                         {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                                        <a class="delete" data-id=""><i class="fa fa-trash-alt"></i></a>
                                           
                                         </form>
                                    
                                </div></td>
                       
                    </tr>
                    
                     @endforeach
            </tbody>
        </table>
    </div>
<ul class="pagination">
        {{ $offers->render() }}
    </ul>
</div>
<script type="text/javascript">
    
    $(function () {
        $('.delete').click(function(e){
            e.preventDefault();
            if(confirm('Are you sure you want to delete?'))
            {
                $(this).parent('form').submit();
            }else{
                return false;
            }
        });
});

    
</script>
@endsection

resources/views/offers/more.blade.php
@extends('layouts.app')
@section('content')
<style type="text/css">
    .box .row{
         margin-bottom: 15px;
    }
</style>
    <div class="row">
    <div class="col-md-12">
            <div class="col-md-6">
                <h1 class="box-title">Offer Details  </h1>
            </div>    
    <div class="pull-right box-tools">
                    <a href="{{URL::to('dashboard/offers')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default btn-default" type="button" data-original-title="Service List">
                            <i class="fa fa-list"></i>
                        </button>
                    </a>
     @if(isset($offer))
                    <a href="{{URL::to('dashboard/offers/create')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default" type="button" data-original-title="Add Offer">
                            <i class="fa fa-plus"></i>
                        </button>
                    </a>
   
                    <a href="{{URL::to('dashboard/offers/'.$offer->id.'/edit')}}">
                        <button title="" data-toggle="tooltip" class="btn btn-default" type="button" data-original-title="Edit Offer">
                            <i class="fa fa-edit"></i>
                        </button>
                    </a>
    @endif               
                </div>
    </div>            
    </div>
        <div class="box">
            <div class="box-body pad" id="tab_1">
                <div class="row">
                    <label class="col-sm-3 control-label">Offer Name</label>
                    <div class="col-sm-6">
                        {{ $offer->name }}
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-3 control-label">Offer Value</label>
                    <div class="col-sm-3">
                        {{ $offer->value }}%
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-3 control-label">Offer Image</label>
                    <div class="col-sm-3">
                        @if(!empty($offer->image))
                                    <a href="javascript:void(0)" class="pop" imgsrc="{{asset($offer->space_image)}}"><img src=" {{ asset($offer->image) }}" class="img-responsive img-rounded" width="150" height="1150" /></a>
                        @else
                            <img src="{{asset('assets/images/no-image.png')}}" />
                        @endif
                    </div>
                </div>
              
        </div>
    </div>
@endsection